---

- name: Remove default debian packaged docker
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine

- name: Install Docker
  apt:
    name: "{{ docker_pkg_name }}"
    state: "{{ docker_pkg_state }}"
    update_cache: true

- name: Install Docker Python Module
  apt:
    name: "{{ docker_py_pkg_name | default('python-docker') }}"
    state: "{{ docker_py_pkg_state | default('latest') }}"
  when:
    - docker_install_py_module
